### ISSUE TITLE
'silent_unregister' missing in django 1.3

### ISSUE THREAD

**Issue by hoffmannkrzysztof** [saxix/django-iadmin#3]
Hi, 
first of all good work i was waiting for that type of extension. 
Unfortunately i cant run test project on django 1.3. I ran tests and this came out:

ERROR: test_templatetags_result_headers (iadmin.tests.comp.CompatibilityTest)
## TemplateSyntaxError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/iadmin/tests/comp.py", line 21, in test_templatetags_result_headers
    admin.autodiscover()
  File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/**init**.py", line 26, in autodiscover
    import_module('%s.admin' % app)
  File "/usr/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/home/krzysiek/Aptana Studio 3 Workspace/testiadmin/src/testiadmin/geo/admin.py", line 45, in <module>
    import iadmin.shortcuts.auth
  File "/usr/local/lib/python2.7/site-packages/iadmin/shortcuts/auth.py", line 57, in <module>
    admin.site.silent_unregister(User)
AttributeError: 'IAdminSite' object has no attribute 'silent_unregister'
#

**Comment by saxix** [comment]
please pull last commit, I removed that tests 'cause wrong.... sorry

sax

2011/7/6 krzysiekpl <
reply@reply.github.com>

**Comment by saxix** [comment]
issue caused by erroneus test
